package visao;

import controle.Controle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import modelo.Senha;
import util.Tipo;

/**
 *
 * @author Vinicius
 */
public class DistribuirSenhasGUI extends javax.swing.JFrame {

    private Controle controle;
    private Senha senha;
    SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");

    public DistribuirSenhasGUI(Controle controle) {
        initComponents();
        this.controle = controle;
        buttonGroup1.add(jRadioButtonComum);
        buttonGroup1.add(jRadioButtonVIP);
        buttonGroup1.add(jRadioButtonPreferencial);
        jLabelHora.setText(format.format(new Date()));
        timer();
    }

//    DistribuirSenhasGUI() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    public void timer() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jLabelHora.setText(format.format(new Date()));
            }
        });
        timer.setRepeats(true);
        timer.start();
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonComum = new javax.swing.JRadioButton();
        jRadioButtonVIP = new javax.swing.JRadioButton();
        jRadioButtonPreferencial = new javax.swing.JRadioButton();
        jButtonRetirar = new javax.swing.JButton();
        jButtonChamar = new javax.swing.JButton();
        jButtonSenhaAtual = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setText("ON BANK");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("SAJ");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Senha de atendimento:");

        jRadioButtonComum.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jRadioButtonComum.setText("Caixas");
        jRadioButtonComum.setToolTipText("Caixas");
        jRadioButtonComum.setOpaque(false);
        jRadioButtonComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonComumActionPerformed(evt);
            }
        });

        jRadioButtonVIP.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jRadioButtonVIP.setText("ON Bank Uniclass");
        jRadioButtonVIP.setToolTipText("ON Bank Uniclass");
        jRadioButtonVIP.setOpaque(false);
        jRadioButtonVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVIPActionPerformed(evt);
            }
        });

        jRadioButtonPreferencial.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jRadioButtonPreferencial.setText("Mesas de Atendimento");
        jRadioButtonPreferencial.setToolTipText("Mesas de Atendimento");
        jRadioButtonPreferencial.setOpaque(false);
        jRadioButtonPreferencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPreferencialActionPerformed(evt);
            }
        });

        jButtonRetirar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonRetirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-impressão-50 (1).png"))); // NOI18N
        jButtonRetirar.setToolTipText("Imprimir Senha");
        jButtonRetirar.setBorderPainted(false);
        jButtonRetirar.setContentAreaFilled(false);
        jButtonRetirar.setName(""); // NOI18N
        jButtonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarActionPerformed(evt);
            }
        });

        jButtonChamar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonChamar.setText("Tela de chamada");
        jButtonChamar.setToolTipText("Tela de chamada");
        jButtonChamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChamarActionPerformed(evt);
            }
        });

        jButtonSenhaAtual.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButtonSenhaAtual.setText("Tela Senha Atual");
        jButtonSenhaAtual.setToolTipText("Tela Senha Atual");
        jButtonSenhaAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSenhaAtualActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 3, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("developed by Vinicius / Lucas / Denes");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Horário Atual:");
        jLabel2.setFocusCycleRoot(true);

        jLabelHora.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(240, 240, 240));
        jLabelHora.setText("00:00:00");
        jLabelHora.setFocusCycleRoot(true);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/download.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonVIP)
                                            .addComponent(jRadioButtonComum))
                                        .addGap(60, 60, 60))
                                    .addComponent(jRadioButtonPreferencial))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRetirar)))
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(291, 291, 291))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(195, 195, 195)
                                        .addComponent(jLabel2)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabelHora))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jButtonChamar)
                                        .addGap(76, 76, 76)
                                        .addComponent(jButtonSenhaAtual)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonComum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonVIP))
                    .addComponent(jButtonRetirar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonPreferencial)
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSenhaAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonChamar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabelHora)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonComumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonComumActionPerformed

    private void jRadioButtonVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonVIPActionPerformed

    private void jRadioButtonPreferencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPreferencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPreferencialActionPerformed

    private void jButtonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarActionPerformed
        // TODO add your handling code here:
        int tipo;
        if (jRadioButtonComum.isSelected()) {
            tipo = Tipo.COMUM;
        } else if (jRadioButtonVIP.isSelected()) {
            tipo = Tipo.VIP;
        } else if (jRadioButtonPreferencial.isSelected()) {
            tipo = Tipo.PREFERENCIAL;
        } else {
            tipo = Tipo.COMUM;
        }
        senha = controle.emitirSenha(tipo, new Date());
        JOptionPane.showMessageDialog(this, "Sua senha é " + senha.getId() + "\n Retirada às " + format.format(senha.getHoraretirada()),
            "Senha retirada", JOptionPane.INFORMATION_MESSAGE);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButtonRetirarActionPerformed

    private void jButtonChamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChamarActionPerformed
        // TODO add your handling code here:
        controle.abrirTelaChamarCliente();
        controle.fecharTelaDistribuirSenha();
    }//GEN-LAST:event_jButtonChamarActionPerformed

    private void jButtonSenhaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSenhaAtualActionPerformed
        // TODO add your handling code here:
        controle.abrirTelaSenhaAtual();
        controle.fecharTelaDistribuirSenha();
    }//GEN-LAST:event_jButtonSenhaAtualActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonChamar;
    private javax.swing.JButton jButtonRetirar;
    private javax.swing.JButton jButtonSenhaAtual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonComum;
    private javax.swing.JRadioButton jRadioButtonPreferencial;
    private javax.swing.JRadioButton jRadioButtonVIP;
    // End of variables declaration//GEN-END:variables
}
